name: "yolo_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 16

dynamic_batching {
  max_queue_delay_microseconds: 5000
}

input[
  {
    name: "images"
    data_type: TYPE_FP32
    dims:[ 3, 640, 640 ]
  }
]

output[
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 84, -1 ]
  }
]
